name: Build and deploy Java app
 
on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Maven
        run: |
          echo "export JAVA_HOME=${RUNNER_TOOL_CACHE}/java/11.0.12-7/ > ~/.bashrc"
          source ~/.bashrc
          echo "JAVA_HOME set to ${JAVA_HOME}"
          echo "Maven is installed in $(which mvn)"
        shell: bash

      - name: Build with Maven
        run: |
          cd /home/runner/work/github-action-java/github-action-java/java-project
          mvn clean install -Drakesh-test=rakesh-test
          
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rak-artifact  # Name for the artifact
          path: /home/runner/.m2/repository/helloworld/helloworld/1.0-SNAPSHOT/helloworld-1.0-SNAPSHOT.war  # Path to the JAR file or any other artifacts you want to publish

  deploy:
      name: Deploy
      needs: build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
   
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: rak-artifact
            path: _site/
        - name: Configure Git
          run: |
            git config --global user.email "rakesh.patil3419@gmail.com"
            git config --global user.name "rakeshgp993"

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GH_PAGES_TOKEN }}
            publish_dir: _site/

  ## deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: .net-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'phoenix123'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_93245C1B3B574C66955875BD6B1FEE3B }}
  #         package: .
