name: Build and deploy Java app
 
on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 17
          distribution: jdk
    # The package type (jdk, jre, jdk+fx, jre+fx)
      # - name: Setup Java
      #   uses: Fleshgrinder/setup-java@1.0.0
      #   with:
      #     version: 1.0.0
 
  #     - name: Build with dotnet
  #       run: dotnet build Phoenix.Web --configuration Release

  #     - name: Apache Maven Build Automation for Java Project
  #       uses: NishkarshRaj/Maven_Actions@0.1
  #       with:
  #         # Apache Maven hierarchy to be followed in src/main/java/{pkg name} for source code
  #         src: src/main/java/com/microsoft/demo/Demo.java

  #     # - name: dotnet publish
  #     #   run: dotnet publish Phoenix.Web -c Release -o ${{env.DOTNET_ROOT}}/myapp
  #     - name: Java Maven release
  #     # You may pin to the exact commit or the version.
  #     # uses: qcastel/github-actions-maven-release@88522b1841bc65c43d7040c15b0ac0867c2fa7ea
  #       uses: qcastel/github-actions-maven-release@v1.12.31
  #       with:
  #         release-branch-name: master
  #     # - name: Upload artifact for deployment job
  #     #   uses: actions/upload-artifact@v2
  #     #   with:
  #     #     name: .net-app
  #     #     path: ${{env.DOTNET_ROOT}}/myapp

  #     - name: Upload GitHub Pages artifact
  #       uses: actions/upload-pages-artifact@v3.0.0
  #       with:
  #         # Artifact name
  #         name: java-app #  optional, default is github-pages
  #         # Path of the directory containing the static assets.
  #         path: _site/ # default is _site/


  # deploy:
  #     name: Deploy
  #     needs: build
  #     runs-on: ubuntu-latest
  #     if: github.ref == 'refs/heads/master'
   
  #     steps:
  #       - name: Download artifact
  #         uses: actions/download-artifact@v2
  #         with:
  #           name: java-app
  #           path: _site/
   
  #       - name: Deploy to GitHub Pages
  #         uses: peaceiris/actions-gh-pages@v3
  #         with:
  #           github_token: ${{ secrets.TOKEN }}
  #           publish_dir: _site/

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: .net-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'phoenix123'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_93245C1B3B574C66955875BD6B1FEE3B }}
  #         package: .
