name: Build and deploy Java app
 
on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Maven
        run: |
          echo "export JAVA_HOME=${RUNNER_TOOL_CACHE}/java/11.0.12-7/ > ~/.bashrc"
          source ~/.bashrc
          echo "JAVA_HOME set to ${JAVA_HOME}"
          echo "Maven is installed in $(which mvn)"
        shell: bash

      - name: Build with Maven
        run: |
          cd /home/runner/work/github-action-java/github-action-java/java-project
          mvn clean install -Drakesh-test=rakesh-test

    - name: Build with Maven
      run: |
        cd your_project_directory  # Change to the correct directory where your pom.xml is located
        mvn clean install -Drakesh-test=rakesh-test

        
  #     # - name: dotnet publish
  #     #   run: dotnet publish Phoenix.Web -c Release -o ${{env.DOTNET_ROOT}}/myapp
  #     - name: Java Maven release
  #     # You may pin to the exact commit or the version.
  #     # uses: qcastel/github-actions-maven-release@88522b1841bc65c43d7040c15b0ac0867c2fa7ea
  #       uses: qcastel/github-actions-maven-release@v1.12.31
  #       with:
  #         release-branch-name: master
  #     # - name: Upload artifact for deployment job
  #     #   uses: actions/upload-artifact@v2
  #     #   with:
  #     #     name: .net-app
  #     #     path: ${{env.DOTNET_ROOT}}/myapp

  #     - name: Upload GitHub Pages artifact
  #       uses: actions/upload-pages-artifact@v3.0.0
  #       with:
  #         # Artifact name
  #         name: java-app #  optional, default is github-pages
  #         # Path of the directory containing the static assets.
  #         path: _site/ # default is _site/


  # deploy:
  #     name: Deploy
  #     needs: build
  #     runs-on: ubuntu-latest
  #     if: github.ref == 'refs/heads/master'
   
  #     steps:
  #       - name: Download artifact
  #         uses: actions/download-artifact@v2
  #         with:
  #           name: java-app
  #           path: _site/
   
  #       - name: Deploy to GitHub Pages
  #         uses: peaceiris/actions-gh-pages@v3
  #         with:
  #           github_token: ${{ secrets.TOKEN }}
  #           publish_dir: _site/

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
 
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: .net-app
 
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'phoenix123'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_93245C1B3B574C66955875BD6B1FEE3B }}
  #         package: .
